---
- hosts: localhost
  tasks:
  - name: "Installing Palworld Server. If this fails make sure steamcmd is installed"
    shell: "/usr/games/steamcmd +login anonymous +force_install_dir {{app_dir}}/palworld +app_update 2394010 -validate +quit"
