---
- hosts: localhost
  tasks:
  - name: "Starting Palworld Server! {{hostname}}"
    shell: ps aux | grep -ie "{{identity}}" | grep -v grep | awk '{print $2}' | xargs kill -9
  - name: "Starting up Palworld server. Log: {{app_dir}}/logs/palworld-services.log"
    shell: cd {{app_dir}}/palworld/ && nohup ./palworld -batchmode +server.ip 0.0.0.0 +server.port {{server_port}} +server.tickrate 10 +server.hostname "{{hostname}}" +server.identity "{{identity}}" +server.seed {{seed}} +server.maxplayers {{players}} +server.worldsize {{worldsize}} +server.saveinterval 600 +rcon.ip 0.0.0.0 +rcon.port {{rcon_port}} +rcon.password "{{rcon_password}}" +server.description "{{description}}" +server.headerimage "{{header_image}}" +app.port {{app_port}} >> {{app_dir}}/logs/palworld-services.log 2>&1&
